Update update-lists.yml

diff --git a/.github/workflows/update-lists.yml b/.github/workflows/update-lists.yml
--- a/.github/workflows/update-lists.yml
+++ b/.github/workflows/update-lists.yml
@@ -16,10 +16,27 @@ jobs:
         fetch-depth: 0 
 
     - name: Download M3U8 files
-      run:
+      run: |
           echo "Scraping Streamed"
           curl -fSL "https://streamed.su/api/matches/all" -o "output.json"
 
+    - name: Log the downloaded M3U8 file details
+      run: |
+          if [ -f "output.json ]; then
+            echo "output.json downloaded successfully."
+            ls -lh "output.json"
+          else
+            echo "Failed to download output.json."
+          fi
+
+
+    - name: Commit and push the M3U8 files (Squash Commit)
+      run: |
+          git config --global user.name "actions-user"
+          git config --global user.email "actions@github.com"
+          git add "output.json"
+          git commit -m "Scraped" || echo "No changes to commit"
+          git push --force-with-lease
 
     - name: Set up PHP
       uses: shivammathur/setup-php@v2
